package com.example.util

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import androidx.core.content.FileProvider
import com.example.data.db.FlashcardEntity
import com.example.data.db.StudyNoteEntity
import com.example.model.GeneratedDoubtResponse
import com.example.model.GeneratedFlashcardItem
import com.example.model.GeneratedStudyNotes
import java.io.File
import java.io.FileOutputStream

object PdfExporter {

    private const val PAGE_WIDTH = 595
    private const val PAGE_HEIGHT = 842
    private const val MARGIN_LEFT = 40f
    private const val MARGIN_RIGHT = 40f
    private const val MARGIN_TOP = 40f
    private const val MARGIN_BOTTOM = 50f
    private const val PRINTABLE_WIDTH = (PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT).toInt()

    // Primary Colors for PDF styling (RGB)
    private val COLOR_PRIMARY = Color.rgb(24, 90, 157)      // Deep Blue #185A9D
    private val COLOR_SECONDARY = Color.rgb(67, 160, 71)    // Muted Green #43A047
    private val COLOR_ACCENT = Color.rgb(230, 81, 0)        // Deep Orange #E65100
    private val COLOR_TEXT_DARK = Color.rgb(33, 33, 33)     // Dark Charcoal #212121
    private val COLOR_TEXT_MUTED = Color.rgb(117, 117, 117)  // Gray #757575
    private val COLOR_BG_LIGHT = Color.rgb(245, 247, 250)   // Light gray/blue box fill
    private val COLOR_BORDER = Color.rgb(220, 224, 230)     // Border gray

    private class PdfPageManager(val document: PdfDocument, val documentTitle: String) {
        var pageNum = 0
        var currentY = MARGIN_TOP
        var currentPage: PdfDocument.Page? = null
        var canvas: Canvas? = null

        fun startNewPage(): Canvas {
            currentPage?.let {
                drawFooter(it.canvas, pageNum)
                document.finishPage(it)
            }
            pageNum++
            val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNum).create()
            val newPage = document.startPage(pageInfo)
            currentPage = newPage
            val c = newPage.canvas
            canvas = c
            drawHeader(c)
            currentY = MARGIN_TOP + 35f
            return c
        }

        fun ensureSpace(neededHeight: Float): Canvas {
            val currentCanvas = canvas
            if (currentCanvas == null || currentY + neededHeight > (PAGE_HEIGHT - MARGIN_BOTTOM)) {
                return startNewPage()
            }
            return currentCanvas
        }

        fun finish() {
            currentPage?.let {
                drawFooter(it.canvas, pageNum)
                document.finishPage(it)
                currentPage = null
            }
        }

        private fun drawHeader(c: Canvas) {
            val paint = Paint().apply {
                color = COLOR_PRIMARY
                textSize = 9f
                isAntiAlias = true
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            }
            c.drawText(documentTitle.uppercase(), MARGIN_LEFT, MARGIN_TOP, paint)

            val linePaint = Paint().apply {
                color = COLOR_BORDER
                strokeWidth = 1f
            }
            c.drawLine(MARGIN_LEFT, MARGIN_TOP + 8f, PAGE_WIDTH - MARGIN_RIGHT, MARGIN_TOP + 8f, linePaint)
        }

        private fun drawFooter(c: Canvas, page: Int) {
            val linePaint = Paint().apply {
                color = COLOR_BORDER
                strokeWidth = 1f
            }
            val footerY = PAGE_HEIGHT - MARGIN_BOTTOM + 15f
            c.drawLine(MARGIN_LEFT, footerY - 10f, PAGE_WIDTH - MARGIN_RIGHT, footerY - 10f, linePaint)

            val paint = Paint().apply {
                color = COLOR_TEXT_MUTED
                textSize = 9f
                isAntiAlias = true
                typeface = Typeface.DEFAULT
            }
            c.drawText("Generated by Anshu Mock AI Study Tools", MARGIN_LEFT, footerY, paint)

            val pageStr = "Page $page"
            val pageStrWidth = paint.measureText(pageStr)
            c.drawText(pageStr, PAGE_WIDTH - MARGIN_RIGHT - pageStrWidth, footerY, paint)
        }
    }

    private fun drawStaticText(
        pageMgr: PdfPageManager,
        text: String,
        textSize: Float,
        color: Int,
        isBold: Boolean = false,
        spacingAfter: Float = 8f
    ) {
        if (text.isBlank()) return

        val textPaint = TextPaint().apply {
            this.color = color
            this.textSize = textSize
            this.isAntiAlias = true
            this.typeface = if (isBold) Typeface.create(Typeface.DEFAULT, Typeface.BOLD) else Typeface.DEFAULT
        }

        val builder = StaticLayout.Builder.obtain(text, 0, text.length, textPaint, PRINTABLE_WIDTH)
            .setAlignment(Layout.Alignment.ALIGN_NORMAL)
            .setLineSpacing(0f, 1.15f)
            .setIncludePad(true)
        val layout = builder.build()

        val neededHeight = layout.height.toFloat() + spacingAfter
        val canvas = pageMgr.ensureSpace(neededHeight)

        canvas.save()
        canvas.translate(MARGIN_LEFT, pageMgr.currentY)
        layout.draw(canvas)
        canvas.restore()

        pageMgr.currentY += neededHeight
    }

    private fun drawBulletItem(
        pageMgr: PdfPageManager,
        text: String,
        bulletColor: Int = COLOR_PRIMARY,
        textSize: Float = 11f
    ) {
        if (text.isBlank()) return

        val bulletMargin = 16f
        val textWidth = PRINTABLE_WIDTH - bulletMargin.toInt()

        val textPaint = TextPaint().apply {
            this.color = COLOR_TEXT_DARK
            this.textSize = textSize
            this.isAntiAlias = true
            this.typeface = Typeface.DEFAULT
        }

        val builder = StaticLayout.Builder.obtain(text, 0, text.length, textPaint, textWidth)
            .setAlignment(Layout.Alignment.ALIGN_NORMAL)
            .setLineSpacing(0f, 1.15f)
            .setIncludePad(true)
        val layout = builder.build()

        val neededHeight = layout.height.toFloat() + 6f
        val canvas = pageMgr.ensureSpace(neededHeight)

        val bulletPaint = Paint().apply {
            color = bulletColor
            isAntiAlias = true
        }
        canvas.drawCircle(MARGIN_LEFT + 6f, pageMgr.currentY + (textSize / 1.5f), 3f, bulletPaint)

        canvas.save()
        canvas.translate(MARGIN_LEFT + bulletMargin, pageMgr.currentY)
        layout.draw(canvas)
        canvas.restore()

        pageMgr.currentY += neededHeight
    }

    private fun drawSectionHeader(
        pageMgr: PdfPageManager,
        title: String,
        color: Int = COLOR_PRIMARY
    ) {
        val paint = TextPaint().apply {
            this.color = color
            this.textSize = 12f
            this.isAntiAlias = true
            this.typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }

        val neededHeight = 26f
        val canvas = pageMgr.ensureSpace(neededHeight)

        canvas.save()
        canvas.translate(MARGIN_LEFT, pageMgr.currentY)

        val bgPaint = Paint().apply {
            this.color = COLOR_BG_LIGHT
            this.style = Paint.Style.FILL
        }
        canvas.drawRoundRect(0f, 0f, PRINTABLE_WIDTH.toFloat(), 22f, 6f, 6f, bgPaint)

        val borderPaint = Paint().apply {
            this.color = color
            this.style = Paint.Style.STROKE
            this.strokeWidth = 2f
        }
        canvas.drawLine(0f, 0f, 0f, 22f, borderPaint)

        canvas.drawText(title, 12f, 15f, paint)
        canvas.restore()

        pageMgr.currentY += neededHeight
    }

    fun generateStudyNotesPdf(
        context: Context,
        subject: String,
        topic: String,
        language: String,
        notes: GeneratedStudyNotes
    ): File? {
        val doc = PdfDocument()
        val pageMgr = PdfPageManager(doc, "ANSHU MOCK AI STUDY NOTES")
        pageMgr.startNewPage()

        drawStaticText(pageMgr, notes.title.ifBlank { "$topic Study Notes" }, 18f, COLOR_PRIMARY, isBold = true, spacingAfter = 4f)
        drawStaticText(pageMgr, "Subject: $subject  |  Topic: $topic  |  Language: $language", 10f, COLOR_TEXT_MUTED, isBold = false, spacingAfter = 16f)

        if (notes.summary.isNotBlank()) {
            drawSectionHeader(pageMgr, "SUMMARY", COLOR_PRIMARY)
            drawStaticText(pageMgr, notes.summary, 11f, COLOR_TEXT_DARK, spacingAfter = 14f)
        }

        if (notes.importantConcepts.isNotEmpty()) {
            drawSectionHeader(pageMgr, "IMPORTANT CONCEPTS", COLOR_PRIMARY)
            notes.importantConcepts.forEach { drawBulletItem(pageMgr, it, COLOR_PRIMARY) }
            pageMgr.currentY += 8f
        }

        if (notes.keyDefinitions.isNotEmpty()) {
            drawSectionHeader(pageMgr, "KEY DEFINITIONS", COLOR_SECONDARY)
            notes.keyDefinitions.forEach { drawBulletItem(pageMgr, it, COLOR_SECONDARY) }
            pageMgr.currentY += 8f
        }

        if (notes.examPoints.isNotEmpty()) {
            drawSectionHeader(pageMgr, "HIGH-YIELD EXAM POINTS", COLOR_ACCENT)
            notes.examPoints.forEach { drawBulletItem(pageMgr, it, COLOR_ACCENT) }
            pageMgr.currentY += 8f
        }

        if (notes.examples.isNotEmpty()) {
            drawSectionHeader(pageMgr, "EXAMPLES & APPLICATIONS", COLOR_PRIMARY)
            notes.examples.forEach { drawBulletItem(pageMgr, it, COLOR_PRIMARY) }
            pageMgr.currentY += 8f
        }

        if (notes.quickRevision.isNotEmpty()) {
            drawSectionHeader(pageMgr, "QUICK REVISION POINTS", COLOR_ACCENT)
            notes.quickRevision.forEach { drawBulletItem(pageMgr, it, COLOR_ACCENT) }
            pageMgr.currentY += 8f
        }

        pageMgr.finish()

        val sanitizeName = topic.replace(Regex("[^a-zA-Z0-9_]"), "_").take(20)
        val file = File(context.cacheDir, "StudyNotes_${sanitizeName}_${System.currentTimeMillis()}.pdf")
        return try {
            doc.writeTo(FileOutputStream(file))
            doc.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            doc.close()
            null
        }
    }

    fun generateFlashcardsPdf(
        context: Context,
        subject: String,
        topic: String,
        language: String,
        cards: List<GeneratedFlashcardItem>
    ): File? {
        val doc = PdfDocument()
        val pageMgr = PdfPageManager(doc, "ANSHU MOCK AI FLASHCARDS")
        pageMgr.startNewPage()

        drawStaticText(pageMgr, "$topic Flashcard Deck", 18f, COLOR_PRIMARY, isBold = true, spacingAfter = 4f)
        drawStaticText(pageMgr, "Subject: $subject  |  Topic: $topic  |  Language: $language  |  Total Cards: ${cards.size}", 10f, COLOR_TEXT_MUTED, isBold = false, spacingAfter = 16f)

        cards.forEachIndexed { index, card ->
            val cardTitle = "FLASHCARD #${index + 1}"
            drawSectionHeader(pageMgr, cardTitle, COLOR_PRIMARY)

            drawStaticText(pageMgr, "Question / Concept:", 10f, COLOR_PRIMARY, isBold = true, spacingAfter = 2f)
            drawStaticText(pageMgr, card.frontText, 11f, COLOR_TEXT_DARK, isBold = true, spacingAfter = 6f)

            drawStaticText(pageMgr, "Answer / Explanation:", 10f, COLOR_SECONDARY, isBold = true, spacingAfter = 2f)
            drawStaticText(pageMgr, card.backText, 11f, COLOR_TEXT_DARK, isBold = false, spacingAfter = 16f)
        }

        pageMgr.finish()

        val sanitizeName = topic.replace(Regex("[^a-zA-Z0-9_]"), "_").take(20)
        val file = File(context.cacheDir, "Flashcards_${sanitizeName}_${System.currentTimeMillis()}.pdf")
        return try {
            doc.writeTo(FileOutputStream(file))
            doc.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            doc.close()
            null
        }
    }

    fun generateFlashcardsPdfFromEntities(
        context: Context,
        subject: String,
        topic: String,
        language: String,
        cards: List<FlashcardEntity>
    ): File? {
        val items = cards.map { GeneratedFlashcardItem(frontText = it.frontText, backText = it.backText) }
        return generateFlashcardsPdf(context, subject, topic, language, items)
    }

    fun generateDoubtPdf(
        context: Context,
        subject: String,
        topic: String,
        language: String,
        question: String,
        response: GeneratedDoubtResponse
    ): File? {
        val doc = PdfDocument()
        val pageMgr = PdfPageManager(doc, "ANSHU MOCK AI DOUBT SOLVER")
        pageMgr.startNewPage()

        drawStaticText(pageMgr, "AI Doubt Explanation", 18f, COLOR_PRIMARY, isBold = true, spacingAfter = 4f)
        val meta = buildString {
            if (subject.isNotBlank()) append("Subject: $subject  |  ")
            if (topic.isNotBlank()) append("Topic: $topic  |  ")
            append("Language: $language")
        }
        drawStaticText(pageMgr, meta, 10f, COLOR_TEXT_MUTED, isBold = false, spacingAfter = 14f)

        drawSectionHeader(pageMgr, "QUESTION / DOUBT", COLOR_PRIMARY)
        drawStaticText(pageMgr, question, 11f, COLOR_TEXT_DARK, isBold = true, spacingAfter = 14f)

        if (response.directAnswer.isNotBlank()) {
            drawSectionHeader(pageMgr, "DIRECT ANSWER", COLOR_SECONDARY)
            drawStaticText(pageMgr, response.directAnswer, 11f, COLOR_TEXT_DARK, isBold = true, spacingAfter = 14f)
        }

        if (response.simpleExplanation.isNotBlank()) {
            drawSectionHeader(pageMgr, "SIMPLE EXPLANATION", COLOR_PRIMARY)
            drawStaticText(pageMgr, response.simpleExplanation, 11f, COLOR_TEXT_DARK, isBold = false, spacingAfter = 14f)
        }

        if (response.detailedExplanation.isNotBlank()) {
            drawSectionHeader(pageMgr, "STEP-BY-STEP BREAKDOWN", COLOR_PRIMARY)
            drawStaticText(pageMgr, response.detailedExplanation, 11f, COLOR_TEXT_DARK, isBold = false, spacingAfter = 14f)
        }

        if (response.examPoint.isNotBlank()) {
            drawSectionHeader(pageMgr, "KEY EXAM TAKEAWAY", COLOR_ACCENT)
            drawStaticText(pageMgr, response.examPoint, 11f, COLOR_TEXT_DARK, isBold = false, spacingAfter = 14f)
        }

        pageMgr.finish()

        val sanitizeName = question.replace(Regex("[^a-zA-Z0-9_]"), "_").take(15)
        val file = File(context.cacheDir, "Doubt_${sanitizeName}_${System.currentTimeMillis()}.pdf")
        return try {
            doc.writeTo(FileOutputStream(file))
            doc.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            doc.close()
            null
        }
    }

    fun openOrSharePdf(context: Context, file: File, title: String) {
        val authority = "${context.packageName}.fileprovider"
        val uri = FileProvider.getUriForFile(context, authority, file)

        val sendIntent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, title)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }

        val chooser = Intent.createChooser(sendIntent, "Download / Share $title")
        chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        try {
            context.startActivity(chooser)
        } catch (e: Exception) {
            android.util.Log.e("PdfExporter", "Failed to share PDF", e)
            try {
                android.widget.Toast.makeText(context, "Unable to open PDF viewer or sharing app", android.widget.Toast.LENGTH_SHORT).show()
            } catch (_: Exception) {}
        }
    }

    fun exportStudyNotesPdf(
        context: Context,
        notes: GeneratedStudyNotes,
        subject: String = "General",
        topic: String = "Study Notes",
        language: String = "English"
    ) {
        val pdfFile = generateStudyNotesPdf(context, subject, notes.title.ifBlank { topic }, language, notes)
        if (pdfFile != null) {
            openOrSharePdf(context, pdfFile, notes.title.ifBlank { topic })
        }
    }

    fun exportFlashcardsPdf(
        context: Context,
        subject: String,
        topic: String,
        cards: List<FlashcardEntity>,
        language: String = "English"
    ) {
        val pdfFile = generateFlashcardsPdfFromEntities(context, subject, topic, language, cards)
        if (pdfFile != null) {
            openOrSharePdf(context, pdfFile, "$topic Flashcards")
        }
    }

    fun exportDoubtPdf(
        context: Context,
        question: String,
        response: GeneratedDoubtResponse,
        subject: String = "General",
        topic: String = "Doubt",
        language: String = "English"
    ) {
        val pdfFile = generateDoubtPdf(context, subject, topic, language, question, response)
        if (pdfFile != null) {
            openOrSharePdf(context, pdfFile, "AI Doubt Answer")
        }
    }
}
